In [7]:
import polars as pl

df = pl.read_parquet('./data/modelDataDeIdentified.parquet')
df['finalized_label'].value_counts()

shape: (7, 2)
┌─────────────────────┬───────┐
│ finalized_label     ┆ count │
│ ---                 ┆ ---   │
│ cat                 ┆ u32   │
╞═════════════════════╪═══════╡
│ Normal              ┆ 3217  │
│ Hemoglobin_C_Trait  ┆ 141   │
│ Other               ┆ 535   │
│ Sickle_Cell_Trait   ┆ 491   │
│ HGB_SC_Disease      ┆ 116   │
│ Sickle_Cell_Disease ┆ 203   │
│ Beta_Thalassemia    ┆ 308   │
└─────────────────────┴───────┘

In [12]:
for col in df.columns:
    # check if the column is numeric
    if df[col].dtype.is_numeric():
        # check if the column has negative values
        if (df[col] < 0).any():
            print(f"Column '{col}' has negative values.")

In [8]:
df.write_csv('./data/modelDataDeIdentified.csv')

In [3]:
df

shape: (5_011, 58)
┌──────────────┬─────┬──────────────┬───────┬───┬────────────┬───────────┬──────────────┬──────────┐
│ finalized_la ┆ sex ┆ pat_age_at_t ┆ hgb_a ┆ … ┆ prior_iron ┆ prior_nbs ┆ prior_acid_g ┆ weights  │
│ bel          ┆ --- ┆ est          ┆ ---   ┆   ┆ ---        ┆ ---       ┆ el           ┆ ---      │
│ ---          ┆ str ┆ ---          ┆ f64   ┆   ┆ f64        ┆ f64       ┆ ---          ┆ f64      │
│ cat          ┆     ┆ f64          ┆       ┆   ┆            ┆           ┆ f64          ┆          │
╞══════════════╪═════╪══════════════╪═══════╪═══╪════════════╪═══════════╪══════════════╪══════════╡
│ Normal       ┆ F   ┆ 34.294541    ┆ 98.2  ┆ … ┆ 0.0        ┆ 0.0       ┆ 0.0          ┆ 0.561234 │
│ Normal       ┆ M   ┆ 64.047655    ┆ 97.3  ┆ … ┆ 1.0        ┆ 0.0       ┆ 0.0          ┆ 0.561234 │
│ Beta_Thalass ┆ F   ┆ 55.91883     ┆ 94.0  ┆ … ┆ 0.0        ┆ 0.0       ┆ 0.0          ┆ 1.81382  │
│ emia         ┆     ┆              ┆       ┆   ┆            ┆           ┆              ┆          │
│ Normal       ┆ M   ┆ 27.71684     ┆ 97.2  ┆ … ┆ 0.0        ┆ 0.0       ┆ 0.0          ┆ 0.561234 │
│ Normal       ┆ F   ┆ 21.527275    ┆ 97.8  ┆ … ┆ 0.0        ┆ 0.0       ┆ 0.0          ┆ 0.561234 │
│ …            ┆ …   ┆ …            ┆ …     ┆ … ┆ …          ┆ …         ┆ …            ┆ …        │
│ Normal       ┆ F   ┆ 13.845481    ┆ 98.4  ┆ … ┆ 0.0        ┆ 0.0       ┆ 0.0          ┆ 0.561234 │
│ Normal       ┆ F   ┆ 13.078609    ┆ 98.6  ┆ … ┆ 0.0        ┆ 0.0       ┆ 0.0          ┆ 0.561234 │
│ Normal       ┆ M   ┆ 15.15172     ┆ 96.5  ┆ … ┆ 0.0        ┆ 0.0       ┆ 0.0          ┆ 0.561234 │
│ Sickle_Cell_ ┆ M   ┆ 7.483487     ┆ 59.9  ┆ … ┆ 0.0        ┆ 0.0       ┆ 1.0          ┆ 1.436577 │
│ Trait        ┆     ┆              ┆       ┆   ┆            ┆           ┆              ┆          │
│ Normal       ┆ F   ┆ 1.376256     ┆ 96.9  ┆ … ┆ 0.0        ┆ 0.0       ┆ 0.0          ┆ 0.561234 │
└──────────────┴─────┴──────────────┴───────┴───┴────────────┴───────────┴──────────────┴──────────┘

In [ ]:
data_dict = pl.read_csv('./data/data-dictionaryDeIden.csv')
xvars = data_dict.filter(pl.col('role') == 'predictor')['variable'].to_list()

['sex',
 'pat_age_at_test',
 'hgb_a',
 'hgb_f',
 'hgb_s',
 'hgb_c',
 'hgb_a2',
 'hgb_a2_variant',
 'hgb_e',
 'hgb_barts',
 'hgb_h',
 'hgb_d',
 'hgb_other_hgb',
 'total_hgb_count',
 'hgb_a_category',
 'hgb_f_category',
 'hgb_s_category',
 'hgb_c_category',
 'hgb_a2_category',
 'hgb_a2_variant_category',
 'hgb_e_category',
 'hgb_barts_category',
 'hgb_h_category',
 'hgb_d_category',
 'hgb_other_hgb_category',
 'total_hgb_count_category',
 'agar_gel_electrophoresis',
 'hemoglobinopathies',
 'rbc_mean',
 'rbc_sd',
 'hgb_mean',
 'hgb_sd',
 'hct_mean',
 'hct_sd',
 'mcv_mean',
 'mcv_sd',
 'rdw_cv_mean',
 'rdw_cv_sd',
 'calculated_tibc_mean',
 'calculated_tibc_sd',
 'hemolysis_mean',
 'hemolysis_sd',
 'icterus_mean',
 'icterus_sd',
 'iron_mean',
 'iron_sd',
 'tfn_saturation_mean',
 'tfn_saturation_sd',
 'transferrin_mean',
 'transferrin_sd',
 'turbidity_mean',
 'turbidity_sd']